name: "Get the export name for a platform"
description: "Get the export name for a platform, from the export_presets.cfg"

inputs:
  platform:
    description: "The platform to get the export name for"
    required: true

outputs:
  export-name:
    value: ${{ steps.get-export-name.outputs.export-name }}
    description: "The export name for the platform"

runs:
  using: "composite"
  steps:
    - name: Get export name
      id: get-export-name
      run: |
        wget -nv 'https://raw.githubusercontent.com/bend-n/godot-actions/main/.github/actions/get-export-name/get-export-name.py' -O get-export-name.py
        python get-export-name.py "${{ inputs.platform }}" || echo "::notice file=export_presets.cfg,title=Missing Configuration::No export for ${{ inputs.platform }}."
        echo "::set-output name=export-name::$(python get-export-name.py "${{ inputs.platform }}")"
      shell: bash
