name: "Windows export"
description: "Windows export"

runs:
  using: "composite"
  steps:
    - name: Build
      uses: bend-n/godot-actions/.github/actions/export@main
      with:
        extension: exe
        platform: windows
