name: Web export
description: Web export

inputs:
  git-name:
    description: Name of commiter
    required: true
    default: "bendn"
  git-email:
    description: Email of commiter
    required: true
    default: "bend.n@outlook.com"
  github-pages:
    description: To gh pages, or not to gh pages, that is the question.
    required: true
    default: "true"

runs:
  using: composite
  steps:
    - name: Build
      uses: bend-n/godot-actions/.github/actions/export@main
      with:
        name: index
        extension: html
        platform: web

    - name: Test git repo
      id: is-repo
      run: echo "is-repo=$(git rev-parse --is-inside-work-tree || echo false)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Deploy
      if: steps.is-repo.outputs.is-repo == 'true' && inputs.github-pages == 'true'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build/web
        git-config-name: ${{ inputs.git-name }}
        git-config-email: ${{ inputs.git-email }}
        single-commit: true
        silent: true
