name: Web export
description: Web export

inputs:
  git-name:
    description: Name of commiter
    required: true
    default: "bendn"
  git-email:
    description: Email of commiter
    required: true
    default: "bend.n@outlook.com"

runs:
  using: composite
  steps:
    - name: Setup
      uses: bend-n/godot-actions/.github/actions/setup-godot@main

    - name: Web Build
      run: |
        echo "::group::Web Build"
        mkdir -vp build/web
        godot -v --export "HTML" ./build/web/index.html
        echo "::endgroup::"
      shell: bash

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: web
        path: build/web

    - name: Test git repo
      id: is-repo
      run: "echo ::set-output name=is-repo::$(git rev-parse --is-inside-work-tree || echo false)"
      shell: bash

    - name: Deploy
      if: steps.is-repo.outputs.is-repo == 'true'
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        branch: gh-pages
        folder: build/web
        git-config-name: ${{ inputs.git-name }}
        git-config-email: ${{ inputs.git-email }}
        single-commit: true
