name: Linux export
description: Linux export

runs:
  using: composite
  steps:
    - name: Setup
      uses: bend-n/godot-actions/.github/actions/setup-godot@main

    - name: Get export name
      id: get-export-name
      uses: bend-n/godot-actions/.github/actions/get-export-name@main
      with:
        platform: Linux/X11

    - name: Linux Build
      if: steps.get-export-name.outputs.export-name
      run: |
        echo "::group::Linux Build"
        mkdir -vp build/linux
        godot -v --export "${{ steps.get-export-name.outputs.export-name }}" ./build/linux/$NAME.x86_64
        echo "::endgroup::"
      shell: bash

    - uses: actions/upload-artifact@v3
      if: steps.get-export-name.outputs.export-name
      with:
        name: linux
        path: build/linux
