name: Linux export
description: Linux export

runs:
  using: composite
  steps:
    - name: Build
      uses: bend-n/godot-actions/.github/actions/export@main
      with:
        extension: x86_64
        platform: linux
