name: Setup
description: Setup godot and repo

runs:
  using: "composite"
  steps:
    - name: Check if clean
      id: clean
      run: |
        if [[ -z $(find . -mindepth 1 -maxdepth 1) ]]; then echo "::set-output name=clean::true";
        else echo "::set-output name=clean::false"; fi
      shell: bash

    - name: Checkout
      if: steps.clean.outputs.clean == 'true'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
        submodules: recursive

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Setup godot
      run: |
        echo "::group::Setup godot"
        git config --global --add safe.directory $(pwd)
        printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)" > version
        mkdir -v -p ~/.local/share/godot/templates
        [[ -z $RELEASE ]] && RELEASE=stable
        mv /root/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE} ~/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE}
        ls ~/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE} | tr '\n' ' '
        echo "::endgroup::"
      shell: bash
