name: Setup
description: Setup godot and repo

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: true
        submodules: recursive
    - name: Setup
      run: |
        echo "::group::Setup godot"
        git config --global --add safe.directory $(pwd)
        git rev-parse --short HEAD > version
        mkdir -v -p ~/.local/share/godot/templates
        [[ -z $RELEASE ]] && RELEASE=stable
        mv /root/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE} ~/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE}
        ls ~/.local/share/godot/templates/${GODOT_VERSION}.${RELEASE} | tr '\n' ' '
        echo "::endgroup::"
      shell: bash
