name: Setup
description: Setup godot and repo

runs:
  using: "composite"
  steps:
    - name: Check if clean
      id: clean
      run: |
        if [[ -z $(find . -mindepth 1 -maxdepth 1) ]]; then echo "::set-output name=clean::true";
        else echo "::set-output name=clean::false"; fi
      shell: bash

    - name: Checkout
      if: steps.clean.outputs.clean == 'true'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
        submodules: recursive

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Setup godot
      run: |
        echo "::group::Setup godot"

        # config
        mkdir -p ~/.config/godot/
        mv /root/.config/godot/editor_settings-3.tres ~/.config/godot/editor_settings-3.tres
        if [[ -z $PROJECT_PATH ]]; then
          cd "$PROJECT_PATH"
          echo "PROJECT_PATH=." >> $GITHUB_ENV
        fi

        # create version label thing
        git config --global --add safe.directory "$(pwd)" && printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)" > version

        # templates
        [[ -z $RELEASE ]] && RELEASE=stable
        TEMPLATES_PATH=".local/share/godot/templates/${GODOT_VERSION}.${RELEASE}"
        mkdir -p "${HOME}/${TEMPLATES_PATH}"
        mv "/root/${TEMPLATES_PATH}/"* "${HOME}/${TEMPLATES_PATH}"
        ls "${HOME}/${TEMPLATES_PATH}"| tr '\n' ' '

        # gpm
        if [[ -f godot.package ]]; then
          [[ ! -d addons ]] && mkdir addons
          git clone --depth 1 https://github.com/you-win/godot-package-manager
          mv godot-package-manager/addons/godot-package-manager addons/
          rm -rf godot-package-manager
          godot -s addons/godot-package-manager/cli.gd update
          rm -rf addons/godot-package-manager
        fi
        echo "::endgroup::"
      shell: bash
