name: Push to itch.io
description: Push the created artifacts to itch.io

inputs:
  api-key:
    description: The API key for the itch.io account
    required: true
  itch-path:
    description: "The path to the itch.io project eg: leafo/x-moon"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Download
      uses: actions/download-artifact@v3

    - name: Setup butler
      uses: jdno/setup-butler@v1

    - name: Push
      run: |
        [[ -z $ITCH_PATH ]] && ITCH_PATH=bendn/$NAME
        function push() {
          channel=$1
          [[ ! -d $channel ]] && exit 0
          echo "::group::Push $channel"
          [[ $channel == mac ]] && echo -e "#!/bin/bash\n"'cd "$(dirname "$0")"||exit;xattr -cr "$(pwd)/$NAME.app";open -n -a "$(pwd)/$NAME.app"' >./mac/run.sh
          chmod +x **;
          butler push "$channel" "$ITCH_PATH:$channel"
          echo "::endgroup::"
        }
        push "web"; push "linux"; push "windows"; 
        [[ -d mac ]] && unzip "mac/$NAME.zip" -d mac/ && rm "mac/$NAME.zip" && push "mac"
        [[ -d android ]] && rm android/*.idsig && push "android"
      env:
        BUTLER_API_KEY: ${{ inputs.api-key }}
        ITCH_PATH: ${{ inputs.itch-path }}
      shell: bash
