name: Mac export
description: Mac export

runs:
  using: composite
  steps:
    - name: Build
      uses: bend-n/godot-actions/.github/actions/export@main
      with:
        extension: app
        platform: mac
